In [52]:
# bring in relevant libraries
import pandas as pd
import numpy as np
from pathlib import Path

# expand to width of screen
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [53]:
# import file, check output
folder = Path("/Users/gflo247/Desktop/programming/AOC/2022")
filename = "2022aoc2.txt"
with open(folder / filename) as f:
    mylist = f.read().splitlines()
mylist[:20]

['A Y',
 'B Z',
 'C Y',
 'B Y',
 'A Y',
 'A Y',
 'A X',
 'A Y',
 'B Z',
 'A Y',
 'B Y',
 'A Z',
 'A Y',
 'C Z',
 'A Z',
 'A Y',
 'B Y',
 'A Y',
 'A Y',
 'B Z']

In [54]:
# convert list to dataframe, add column name, check output
inp0 = pd.DataFrame(mylist)

# new data frame with split value columns, keep original non-split column
inp1 = inp0[0].str.split(" ", n = 1, expand = True)
inp1 = pd.concat([inp0, inp1], axis=1)

# name columns from new dataframe & check output
inp1.columns = ['both','opp','you']
inp1.head(20)

   both opp you
0   A Y   A   Y
1   B Z   B   Z
2   C Y   C   Y
3   B Y   B   Y
4   A Y   A   Y
5   A Y   A   Y
6   A X   A   X
7   A Y   A   Y
8   B Z   B   Z
9   A Y   A   Y
10  B Y   B   Y
11  A Z   A   Z
12  A Y   A   Y
13  C Z   C   Z
14  A Z   A   Z
15  A Y   A   Y
16  B Y   B   Y
17  A Y   A   Y
18  A Y   A   Y
19  B Z   B   Z

In [55]:
# create letter to rock/paper/scissor translation
ltr_to_rps = {
    'A': 'rock',
    'B': 'paper',
    'C': 'scissors',
    'X': 'rock',
    'Y': 'paper',
    'Z': 'scissors'
}

# create choice translation
rps_to_pts = {
    'X': 1,
    'Y': 2,
    'Z': 3
}

# create result translation
res_to_pts = {
    'A X': 3,
    'A Y': 6,
    'A Z': 0,
    'B X': 0,
    'B Y': 3,
    'B Z': 6,
    'C X': 6,
    'C Y': 0,
    'C Z': 3
}

In [56]:
# apply all the above dictionaries & check output
inp1['rps_opp'] = inp1['opp'].replace(ltr_to_rps)
inp1['rps_you'] = inp1['you'].replace(ltr_to_rps)
inp1['pts_chc'] = inp1['you'].replace(rps_to_pts)
inp1['pts_res'] = inp1['both'].replace(res_to_pts)
inp1['tot_pts'] = inp1['pts_chc'] + inp1['pts_res']
inp1.head(20)

   both opp you   rps_opp   rps_you  pts_chc  pts_res  tot_pts
0   A Y   A   Y      rock     paper        2        6        8
1   B Z   B   Z     paper  scissors        3        6        9
2   C Y   C   Y  scissors     paper        2        0        2
3   B Y   B   Y     paper     paper        2        3        5
4   A Y   A   Y      rock     paper        2        6        8
5   A Y   A   Y      rock     paper        2        6        8
6   A X   A   X      rock      rock        1        3        4
7   A Y   A   Y      rock     paper        2        6        8
8   B Z   B   Z     paper  scissors        3        6        9
9   A Y   A   Y      rock     paper        2        6        8
10  B Y   B   Y     paper     paper        2        3        5
11  A Z   A   Z      rock  scissors        3        0        3
12  A Y   A   Y      rock     paper        2        6        8
13  C Z   C   Z  scissors  scissors        3        3        6
14  A Z   A   Z      rock  scissors        3        0        3
15  A Y   A   Y      rock     paper        2        6        8
16  B Y   B   Y     paper     paper        2        3        5
17  A Y   A   Y      rock     paper        2        6        8
18  A Y   A   Y      rock     paper        2        6        8
19  B Z   B   Z     paper  scissors        3        6        9

In [57]:
sum(inp1['tot_pts'])

15632

In [58]:
# create letter to outcome translation
ltr_to_out = {
    'X': 'lose',
    'Y': 'draw',
    'Z': 'win'
}

# create outcome translation
out_to_pts = {
    'X': 0,
    'Y': 3,
    'Z': 6
}

# create outcome translation
rps_to_pts2 = {
    'rock': 1,
    'paper': 2,
    'scissors': 3
}

# create total points translation
both_to_chc = {
    'A X': 'scissors',
    'A Y': 'rock',
    'A Z': 'paper',
    'B X': 'rock',
    'B Y': 'paper',
    'B Z': 'scissors',
    'C X': 'paper',
    'C Y': 'scissors',
    'C Z': 'rock'
}

In [59]:
# apply all the above dictionaries & check output
inp1['outcome'] = inp1['you'].replace(ltr_to_out)
inp1['chc_new'] = inp1['both'].replace(both_to_chc)
inp1['pts_chc_new'] = inp1['chc_new'].replace(rps_to_pts2)
inp1['pts_out_new'] = inp1['you'].replace(out_to_pts)
inp1['tot_pts_new'] = inp1['pts_chc_new'] + inp1['pts_out_new']
inp1.head(20)

,both,opp,you,rps_opp,rps_you,pts_chc,pts_res,tot_pts,outcome,chc_new,pts_chc_new,pts_out_new,tot_pts_new
0,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
1,B Z,B,Z,paper,scissors,3,6,9,win,scissors,3,6,9
2,C Y,C,Y,scissors,paper,2,0,2,draw,scissors,3,3,6
3,B Y,B,Y,paper,paper,2,3,5,draw,paper,2,3,5
4,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
5,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
6,A X,A,X,rock,rock,1,3,4,lose,scissors,3,0,3
7,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
8,B Z,B,Z,paper,scissors,3,6,9,win,scissors,3,6,9
9,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
10,B Y,B,Y,paper,paper,2,3,5,draw,paper,2,3,5
11,A Z,A,Z,rock,scissors,3,0,3,win,paper,2,6,8
12,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
13,C Z,C,Z,scissors,scissors,3,3,6,win,rock,1,6,7
14,A Z,A,Z,rock,scissors,3,0,3,win,paper,2,6,8
15,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
16,B Y,B,Y,paper,paper,2,3,5,draw,paper,2,3,5
17,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
18,A Y,A,Y,rock,paper,2,6,8,draw,rock,1,3,4
19,B Z,B,Z,paper,scissors,3,6,9,win,scissors,3,6,9

In [60]:
sum(inp1['tot_pts_new'])

14416